import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react'
import type { User } from '@supabase/supabase-js'
import { isCloudConfigured, supabase } from './supabase'

type Status = 'completed' | 'skipped' | 'forgot' | 'unmarked'
type Task = { id: string; title: string; time: string; duration: number; icon: string; detail: string }
type Day = { tasks: Record<string, { status: Status; note: string }>; goal: string; reflection: { learned: string; struggle: string; improve: string; rating: number } }
type Data = { days: Record<number, Day>; theme: 'light' | 'dark' }

const tasks: Task[] = [
  { id: 'dsa', title: 'DSA', time: '09:00 AM – 11:00 AM', duration: 2, icon: '🔥', detail: 'New Learning + Problems' },
  { id: 'system', title: 'System Design', time: '02:00 PM – 04:00 PM', duration: 2, icon: '🏗️', detail: 'Architecture & real-world systems' },
  { id: 'revision', title: 'DSA Revision', time: '05:00 PM – 06:00 PM', duration: 1, icon: '🔄', detail: 'Active recall & old problems' },
  { id: 'development', title: 'Development', time: '07:00 PM – 09:00 PM', duration: 2, icon: '💻', detail: 'New technology & projects' },
]
const key = 'study-challenge-v1'
const newDay = (): Day => ({ tasks: Object.fromEntries(tasks.map(t => [t.id, { status: 'unmarked' as Status, note: '' }])), goal: '', reflection: { learned: '', struggle: '', improve: '', rating: 0 } })
const initial = (): Data => ({ days: Object.fromEntries(Array.from({ length: 30 }, (_, i) => [i + 1, newDay()])), theme: 'light' })
const load = (): Data => { try { const saved = JSON.parse(localStorage.getItem(key) || 'null'); const fresh = initial(); return saved?.days ? { ...fresh, ...saved, days: Object.fromEntries(Object.entries(fresh.days).map(([n, d]) => [n, { ...d, ...saved.days[n], tasks: { ...d.tasks, ...saved.days[n]?.tasks }, reflection: { ...d.reflection, ...saved.days[n]?.reflection } }])) } : fresh } catch { return initial() } }
const normalize = (value: Data): Data => { const fresh = initial(); return { ...fresh, ...value, days: Object.fromEntries(Object.entries(fresh.days).map(([n, d]) => [n, { ...d, ...value.days?.[Number(n)], tasks: { ...d.tasks, ...value.days?.[Number(n)]?.tasks }, reflection: { ...d.reflection, ...value.days?.[Number(n)]?.reflection } }])) } }

const completed = (day: Day) => tasks.filter(t => day.tasks[t.id].status === 'completed').length
const hours = (day: Day) => tasks.reduce((sum, t) => sum + (day.tasks[t.id].status === 'completed' ? t.duration : 0), 0)
const performance = (day: Day) => { const n = completed(day); return n === 4 ? 'great' : n >= 2 ? 'partial' : n ? 'low' : 'empty' }

export default function App() {
  const [data, setData] = useState<Data>(load)
  const [selected, setSelected] = useState(1)
  const [page, setPage] = useState<'dashboard' | 'overview' | 'statistics' | 'notes' | 'sync' | 'settings'>('dashboard')
  const [query, setQuery] = useState('')
  const [cloudUser, setCloudUser] = useState<User | null>(null)
  const [cloudStatus, setCloudStatus] = useState('')
  const importRef = useRef<HTMLInputElement>(null)
  useEffect(() => { localStorage.setItem(key, JSON.stringify(data)); document.documentElement.dataset.theme = data.theme }, [data])
  useEffect(() => { if (!supabase) return; supabase.auth.getUser().then(({ data }) => setCloudUser(data.user)); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => setCloudUser(session?.user ?? null)); return () => listener.subscription.unsubscribe() }, [])
  const stats = useMemo(() => {
    const days = Object.values(data.days); const all = days.flatMap(d => Object.values(d.tasks)); const qualifying = days.map(d => completed(d) >= 3)
    let best = 0, run = 0; qualifying.forEach(ok => { run = ok ? run + 1 : 0; best = Math.max(best, run) })
    let current = 0; for (let i = 29; i >= 0 && qualifying[i]; i--) current++
    const done = all.filter(t => t.status === 'completed').length
    return { done, skipped: all.filter(t => t.status === 'skipped').length, forgot: all.filter(t => t.status === 'forgot').length, hours: days.reduce((n, d) => n + hours(d), 0), percent: Math.round(done / 120 * 100), completedDays: days.filter(d => completed(d) === 4).length, current, best }
  }, [data])
  const day = data.days[selected]
  const updateDay = (fn: (d: Day) => Day) => setData(prev => ({ ...prev, days: { ...prev.days, [selected]: fn(prev.days[selected]) } }))
  const setStatus = (id: string, status: Status) => updateDay(d => ({ ...d, tasks: { ...d.tasks, [id]: { ...d.tasks[id], status: d.tasks[id].status === status ? 'unmarked' : status } } }))
  const setNote = (id: string, note: string) => updateDay(d => ({ ...d, tasks: { ...d.tasks, [id]: { ...d.tasks[id], note } } }))
  const setGoal = (goal: string) => updateDay(d => ({ ...d, goal }))
  const setReflection = (field: keyof Day['reflection'], value: string | number) => updateDay(d => ({ ...d, reflection: { ...d.reflection, [field]: value } }))
  const signIn = async (email: string) => { if (!supabase) return; setCloudStatus('Sending sign-in link…'); const { error } = await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: window.location.origin } }); setCloudStatus(error ? error.message : 'Check your email for the secure sign-in link.') }
  const saveCloud = async () => { if (!supabase || !cloudUser) return; setCloudStatus('Syncing…'); const { error } = await supabase.from('tracker_data').upsert({ user_id: cloudUser.id, data, updated_at: new Date().toISOString() }); setCloudStatus(error ? error.message : 'Synced to the cloud.') }
  const loadCloud = async () => { if (!supabase || !cloudUser) return; setCloudStatus('Loading…'); const { data: row, error } = await supabase.from('tracker_data').select('data').eq('user_id', cloudUser.id).maybeSingle(); if (error) setCloudStatus(error.message); else if (row?.data) { setData(normalize(row.data as Data)); setCloudStatus('Cloud progress loaded.') } else setCloudStatus('No cloud backup yet — choose Sync now to create one.') }
  const signOut = async () => { if (!supabase) return; await supabase.auth.signOut(); setCloudStatus('Signed out. Your local progress remains on this device.') }
  const exportData = () => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'study-challenge-backup.json'; a.click(); URL.revokeObjectURL(url) }
  const importData = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const incoming = JSON.parse(String(reader.result)); if (!incoming.days) throw new Error(); setData({ ...initial(), ...incoming, days: { ...initial().days, ...incoming.days } }); alert('Progress restored successfully.') } catch { alert('That file is not a valid tracker backup.') } }; reader.readAsText(file); event.target.value = '' }
  const navigate = (next: number) => { setSelected(next); setPage('dashboard'); window.scrollTo({ top: 0, behavior: 'smooth' }) }

  const DayPicker = () => <div className="day-picker"><button onClick={() => navigate(Math.max(1, selected - 1))} disabled={selected === 1}>← Previous</button><button className="today" onClick={() => navigate(1)}>Today</button><button onClick={() => navigate(Math.min(30, selected + 1))} disabled={selected === 30}>Next →</button></div>
  const dashboard = <><section className="hero"><div><p className="eyebrow">30-DAY STUDY CHALLENGE</p><h1>Build your consistency,<br/><em>one focused day at a time.</em></h1><p className="muted">Day {selected} of 30 · Daily study target: 7 hours</p></div><div className="hero-ring"><strong>{Math.round(completed(day) / 4 * 100)}%</strong><span>today</span></div></section><section className="metrics"><Metric label="Current day" value={`${selected} / 30`} icon="◷"/><Metric label="Study hours" value={`${stats.hours} / 210`} icon="◒"/><Metric label="Current streak" value={`${stats.current} days`} icon="🔥"/><Metric label="Best streak" value={`${stats.best} days`} icon="🏆"/></section><div className="quick-sync card"><div><strong>{cloudUser ? 'Cloud sync ready' : 'Keep your progress everywhere'}</strong><span>{cloudUser ? 'Save your latest progress securely.' : 'Sign in once to sync across devices.'}</span></div><button onClick={cloudUser ? saveCloud : () => setPage('sync')}>{cloudUser ? '☁ Sync now' : 'Set up sync'}</button></div><DailyGoal goal={day.goal} setGoal={setGoal}/><div className="section-title"><div><p className="eyebrow">TODAY — DAY {selected}</p><h2>Your study schedule</h2></div><DayPicker /></div><div className="schedule">{tasks.map(t => <TaskCard key={t.id} task={t} item={day.tasks[t.id]} onStatus={setStatus} onNote={setNote}/>)}</div><Reflection day={day} set={setReflection}/></>
  const Overview = () => <><div className="page-heading"><p className="eyebrow">PROGRESS AT A GLANCE</p><h1>30-day overview</h1><p className="muted">Click any day to review or update it.</p></div><div className="overview-summary"><strong>{stats.completedDays}</strong><span>perfect days</span><strong>{stats.percent}%</strong><span>overall completion</span></div><div className="calendar">{Array.from({ length: 30 }, (_, i) => { const n = i + 1, d = data.days[n], count = completed(d); return <button key={n} onClick={() => navigate(n)} className={`calendar-day ${performance(d)} ${n === selected ? 'active' : ''}`}><span>DAY</span><b>{String(n).padStart(2, '0')}</b><small>{count ? `${count}/4 done` : 'Not marked'}</small></button> })}</div><div className="legend"><i className="great"/> 4/4 completed <i className="partial"/> Some progress <i className="low"/> Little progress <i className="empty"/> Not marked</div></>
  const Statistics = () => <><div className="page-heading"><p className="eyebrow">YOUR CONSISTENCY</p><h1>Statistics</h1></div><div className="stat-grid"><Metric label="Completion rate" value={`${stats.percent}%`} icon="◉"/><Metric label="Completed tasks" value={`${stats.done} / 120`} icon="✓"/><Metric label="Skipped tasks" value={String(stats.skipped)} icon="×"/><Metric label="Forgot tasks" value={String(stats.forgot)} icon="!"/></div><section className="card chart"><div><h2>Daily performance</h2><p className="muted">Completed study blocks out of 4</p></div><div className="bars">{Array.from({ length: 30 }, (_, i) => <div key={i} title={`Day ${i + 1}: ${completed(data.days[i + 1])}/4`}><span style={{ height: `${completed(data.days[i + 1]) * 25}%` }}/><small>{i + 1}</small></div>)}</div></section></>
  const Notes = () => { const notes = Array.from({ length: 30 }, (_, i) => i + 1).flatMap(n => tasks.filter(t => data.days[n].tasks[t.id].note.trim()).map(t => ({ n, t, note: data.days[n].tasks[t.id].note }))).filter(x => `${x.t.title} ${x.note}`.toLowerCase().includes(query.toLowerCase())); return <><div className="page-heading"><p className="eyebrow">KNOWLEDGE LOG</p><h1>Your study notes</h1><input className="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search notes…"/></div><div className="notes-list">{notes.length ? notes.map(({ n, t, note }) => <button className="note-card" key={`${n}-${t.id}`} onClick={() => navigate(n)}><span>DAY {n} · {t.title}</span><p>{note}</p></button>) : <div className="empty-state">No notes yet. Add a note from any task card and it will appear here.</div>}</div></> }
  const Settings = () => <><div className="page-heading"><p className="eyebrow">PREFERENCES & BACKUP</p><h1>Settings</h1></div><section className="settings card"><div><h2>Appearance</h2><p className="muted">Choose the view that feels most comfortable.</p></div><button onClick={() => setData(d => ({ ...d, theme: d.theme === 'light' ? 'dark' : 'light' }))}>Switch to {data.theme === 'light' ? 'dark' : 'light'} mode</button><hr/><div><h2>Backup your progress</h2><p className="muted">Export a copy or restore it on another device.</p></div><div className="actions"><button onClick={exportData}>Export progress</button><button onClick={() => importRef.current?.click()}>Import progress</button><input ref={importRef} type="file" accept="application/json" onChange={importData} hidden/></div><hr/><div className="danger"><h2>Reset 30-Day Challenge</h2><p>This permanently deletes statuses, notes, and reflections on this device.</p><button onClick={() => { if (confirm('Are you sure? This will permanently delete your 30-day progress, statuses, notes and reflections.')) { setData(initial()); setSelected(1); setPage('dashboard') } }}>Reset challenge</button></div></section></>
  const Sync = () => <><div className="page-heading"><p className="eyebrow">YOUR DATA, EVERYWHERE</p><h1>Cloud sync</h1><p className="muted">Securely keep the same study history on your devices.</p></div><section className="settings card"><CloudSync configured={isCloudConfigured} user={cloudUser} status={cloudStatus} signIn={signIn} save={saveCloud} load={loadCloud} signOut={signOut}/></section></>
  const content = page === 'dashboard' ? dashboard : page === 'overview' ? <Overview/> : page === 'statistics' ? <Statistics/> : page === 'notes' ? <Notes/> : page === 'sync' ? <Sync/> : <Settings/>
  const navItems = [['dashboard','Dashboard','⌂'],['overview','Overview','▦'],['statistics','Stats','◔'],['notes','Notes','▤'],['sync','Sync','☁'],['settings','Settings','⚙']] as const
  return <div className="app"><aside><div className="brand"><span>◈</span> focus<span>.</span></div><nav>{navItems.map(([id, label, icon]) => <button key={id} className={page === id ? 'selected' : ''} onClick={() => setPage(id)}><i>{icon}</i>{label}</button>)}</nav><div className="aside-bottom">7 hour daily target<br/><strong>Small steps. Real progress.</strong></div></aside><main><header><div className="mobile-brand">◈ focus<span>.</span></div><p className="date">PERSONAL STUDY SPACE</p><button className="theme-toggle" onClick={() => setData(d => ({ ...d, theme: d.theme === 'light' ? 'dark' : 'light' }))}>{data.theme === 'light' ? '☾' : '☀'}</button></header>{page === 'dashboard' && <FocusSprint/>}{content}</main><nav className="mobile-nav">{navItems.map(([id, label, icon]) => <button key={id} className={page === id ? 'selected' : ''} onClick={() => setPage(id)}><i>{icon}</i><span>{label}</span></button>)}</nav></div>
}

function Metric({ label, value, icon }: { label: string; value: string; icon: string }) { return <div className="metric card"><span className="metric-icon">{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div> }
function DailyGoal({ goal, setGoal }: { goal: string; setGoal: (goal: string) => void }) { const [draft, setDraft] = useState(goal); useEffect(() => setDraft(goal), [goal]); return <section className="daily-goal card"><div><p className="eyebrow">DAILY GOAL</p><h2>What is your one win today?</h2></div><input value={draft} onChange={e => { setDraft(e.target.value); setGoal(e.target.value) }} placeholder="Example: Finish two binary-search problems" /></section> }
function CloudSync({ configured, user, status, signIn, save, load, signOut }: { configured: boolean; user: User | null; status: string; signIn: (email: string) => void; save: () => void; load: () => void; signOut: () => void }) { const [email, setEmail] = useState(''); if (!configured) return <div className="cloud-sync"><h2>Cloud sync</h2><p className="muted">Add your Supabase environment variables to enable secure cross-device sync.</p></div>; return <div className="cloud-sync"><h2>Cloud sync</h2>{user ? <><p className="muted">Signed in as {user.email}. Your data is private to your account.</p><div className="actions"><button onClick={save}>Sync now</button><button onClick={load}>Load cloud progress</button><button onClick={signOut}>Sign out</button></div></> : <><p className="muted">Sign in with an email link to use the same tracker across every device.</p><div className="sync-login"><input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com"/><button onClick={() => signIn(email)} disabled={!email}>Send sign-in link</button></div></>}{status && <p className="sync-status">{status}</p>}</div> }
function TaskCard({ task, item, onStatus, onNote }: { task: Task; item: { status: Status; note: string }; onStatus: (id: string, s: Status) => void; onNote: (id: string, note: string) => void }) { const [expanded, setExpanded] = useState(Boolean(item.note)); const [draft, setDraft] = useState(item.note); useEffect(() => { if (item.note !== draft) setDraft(item.note) }, [item.note]); const choices: [Status, string, string][] = [['completed','✓ Done','done'],['skipped','× Skip','skip'],['forgot','! Forgot','forgot']]; return <article className={`task-card ${item.status}`}><div className="task-main"><div className="task-time">{task.time}</div><div className="task-title"><span>{task.icon}</span><div><h3>{task.title}</h3><p>{task.detail} <b>· {task.duration}h</b></p></div></div></div><div className="task-actions">{choices.map(([s, label, className]) => <button key={s} className={`${className} ${item.status === s ? 'chosen' : ''}`} onClick={() => onStatus(task.id, s)}>{label}</button>)}<button className="note-button" onClick={() => setExpanded(!expanded)}>⌕ {item.note ? 'Edit notes' : 'Add notes'}</button></div>{expanded && <textarea autoFocus value={draft} onChange={e => { setDraft(e.target.value); onNote(task.id, e.target.value) }} onBlur={() => onNote(task.id, draft)} placeholder={`Add notes for ${task.title}…`} dir="ltr" />}</article> }
function Reflection({ day, set }: { day: Day; set: (f: keyof Day['reflection'], v: string | number) => void }) { const [draft, setDraft] = useState(day.reflection); useEffect(() => setDraft(day.reflection), [day.reflection]); const update = (field: 'learned' | 'struggle' | 'improve', value: string) => { setDraft(d => ({ ...d, [field]: value })); set(field, value) }; return <section className="reflection card"><p className="eyebrow">CLOSE THE DAY</p><h2>Daily reflection</h2><div className="reflection-grid">{([['learned','What did I learn today?'],['struggle','What did I struggle with?'],['improve','What should I improve tomorrow?']] as const).map(([field, label]) => <label key={field}>{label}<textarea value={draft[field]} onChange={e => update(field, e.target.value)} placeholder="Optional…" dir="ltr"/></label>)}</div><div className="rating">Day rating: {[1,2,3,4,5].map(n => <button key={n} onClick={() => set('rating', n)} className={n <= day.reflection.rating ? 'rated' : ''}>★</button>)}</div></section> }

function playAlarm() { const ctx = new (window.AudioContext || (window as any).webkitAudioContext)(); const beep = (time: number, freq: number) => { const osc = ctx.createOscillator(); const gain = ctx.createGain(); osc.connect(gain); gain.connect(ctx.destination); osc.frequency.value = freq; osc.type = 'sine'; gain.gain.setValueAtTime(0.5, time); gain.gain.exponentialRampToValueAtTime(0.001, time + 0.4); osc.start(time); osc.stop(time + 0.4) }; beep(ctx.currentTime, 880); beep(ctx.currentTime + 0.5, 880); beep(ctx.currentTime + 1.0, 1174.66) }
function FocusSprint() { const [seconds, setSeconds] = useState(25 * 60); const [running, setRunning] = useState(false); const [focusTask, setFocusTask] = useState(tasks[0].id); useEffect(() => { if (!running) return; const timer = window.setInterval(() => setSeconds(s => { if (s <= 1) { setRunning(false); playAlarm(); setTimeout(() => alert('Sprint has ended!'), 50); return 0 } return s - 1 }), 1000); return () => window.clearInterval(timer) }, [running]); const hours = Math.floor(seconds / 3600); const minutes = Math.floor((seconds % 3600) / 60); const secs = seconds % 60; const updateTime = (nextHours: number, nextMinutes: number, nextSeconds: number) => { setRunning(false); setSeconds((Math.min(23, Math.max(0, nextHours)) * 3600) + (Math.min(59, Math.max(0, nextMinutes)) * 60) + Math.min(59, Math.max(0, nextSeconds))) }; const field = (label: string, value: number, max: number, change: (value: number) => void, unit: string) => <label><input aria-label={label} type="number" min="0" max={max} value={String(value).padStart(2, '0')} onChange={e => change(Number(e.target.value) || 0)} disabled={running}/><small>{unit}</small></label>; return <section className="focus-sprint card"><div><p className="eyebrow">FOCUS SPRINT</p><div className="timer-inputs">{field('Sprint hours', hours, 23, value => updateTime(value, minutes, secs), 'h')}<span>:</span>{field('Sprint minutes', minutes, 59, value => updateTime(hours, value, secs), 'm')}<span>:</span>{field('Sprint seconds', secs, 59, value => updateTime(hours, minutes, value), 's')}</div><p className="muted">Set your custom hours, minutes, and seconds</p></div><div className="focus-controls"><select aria-label="Focus task" value={focusTask} onChange={e => setFocusTask(e.target.value)} disabled={running}>{tasks.map(t => <option key={t.id} value={t.id}>{t.icon} {t.title}</option>)}</select><button className="sprint-start" onClick={() => setRunning(!running)}>{running ? 'Pause' : seconds === 0 ? 'Done' : 'Start sprint'}</button></div></section> }
